AWSTemplateFormatVersion: '2010-09-09'
Description: Root Cloudformation Template
Resources:
  StackVPC1:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/aa-cloudforms/demo-vpc.yaml
      TimeoutInMinutes: '60'
      Parameters:
        EnvironmentName: "DEMO-VPC1"
        VpcCIDR: "172.31.0.0/16"
        PublicSubnet1CIDR: "172.31.11.0/24"
        PublicSubnet2CIDR: "172.31.12.0/24"
        PrivateSubnet1CIDR: "172.31.21.0/24"
        PrivateSubnet2CIDR: "172.31.22.0/24"
  StackVPC2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/aa-cloudforms/demo-vpc.yaml
      TimeoutInMinutes: '60'
      Parameters:
        EnvironmentName: "DEMO-VPC2"
        VpcCIDR: "172.32.0.0/16"
        PublicSubnet1CIDR: "172.32.11.0/24"
        PublicSubnet2CIDR: "172.32.12.0/24"
        PrivateSubnet1CIDR: "172.32.21.0/24"
        PrivateSubnet2CIDR: "172.32.22.0/24"
  StackVPCPeering:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/aa-cloudforms/demo-vpcpeering.yaml
      TimeoutInMinutes: '60'
      Parameters:
        EnvironmentName: "DEMO-VPCPeering"
        VPCPeer1: { "Fn::GetAtt" : "StackVPC1.Outputs.VPC" }
        VPCPeer2: { "Fn::GetAtt" : "StackVPC2.Outputs.VPC" }
        PublicRouteTableVPC1: { "Fn::GetAtt" : "StackVPC1.Outputs.PublicRouteTable" }
        PrivateRouteTableVPC1: { "Fn::GetAtt" : "StackVPC1.Outputs.PrivateRouteTable" }
        PublicRouteTableVPC2: { "Fn::GetAtt" : "StackVPC2.Outputs.PublicRouteTable" }
        PrivateRouteTableVPC2: { "Fn::GetAtt" : "StackVPC2.Outputs.PrivateRouteTable" }
        CidrVPC1: "172.31.0.0/16"
        CidrVPC2: "172.32.0.0/16"

