Description:
  ASAv 9.10 Instance

Parameters:

  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
    Default: DEMO-EC2-ASAV

  myKeyPair: 
    Description: Amazon EC2 Key Pair
    Type: "AWS::EC2::KeyPair::KeyName"
    Default: AA-TEST-W2

  VPC:
    Description: Parameters passed from parent
    Type: AWS::EC2::VPC::Id

  SubnetPublic:
    Description: Parameters passed from parent
    Type: AWS::EC2::Subnet::Id

  SubnetPrivate:
    Description: Parameters passed from parent
    Type: AWS::EC2::Subnet::Id

  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: m4.xlarge
    AllowedValues:
    - m4.large
    - m4.xlarge

Mappings: 
 RegionMap: 
  "us-east-1": 
   AMI: ""
  "us-east-2":
   AMI: ""
  "us-west-1":
   AMI: "ami-0ea17e02065a25ef3"
  "us-west-2":
   AMI: ""

Resources:

  InstanceSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      Tags:
      - Key: Name
        Value: !Sub ${EnvironmentName} SG
      VpcId: !Ref VPC
      GroupDescription: "Enable ALL"
      SecurityGroupIngress:
        - IpProtocol: -1
          CidrIp: "0.0.0.0/0"


  NetworkInterfaceGIG0:
    Type: AWS::EC2::NetworkInterface
    DependsOn: InstanceSecurityGroup
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} GIG0
      Description: ASAv GIG0/0
      SourceDestCheck: 'false'
      GroupSet:
        - Ref: InstanceSecurityGroup
      SubnetId: !Ref SubnetPrivate

  NetworkInterfaceAttachment:
    Type: AWS::EC2::NetworkInterfaceAttachment
    DependsOn: ASAvInstance1
    Properties:
      InstanceId:
        Ref: ASAvInstance1
      NetworkInterfaceId:
        Ref: NetworkInterfaceGIG0
      DeviceIndex: 1

  ASAvInstance1:
    Type: "AWS::EC2::Instance"
    DependsOn: NetworkInterfaceGIG0
    Properties:
      ImageId: { "Fn::FindInMap" : [ "RegionMap", { "Ref" : "AWS::Region" }, "AMI" ]}
      InstanceType:
        Ref: InstanceType
      KeyName: !Ref myKeyPair
      SubnetId: !Ref SubnetPublic
      SecurityGroupIds:
        - Ref: InstanceSecurityGroup
      UserData:
        Fn::Base64:                                # YAML makes userdata much cleaner DELETE CISCO USER FOR SECURE ACCESS
          !Sub |
            ! required config start
            ! ASA Version 9.10.1.11
            interface management0/0
            management-only
            nameif management
            security-level 100
            ip address dhcp setroute
            no shut
            !
            same-security-traffic permit inter-interface
            same-security-traffic permit intra-interface
            !
            crypto key generate rsa modulus 2048 noconfirm
            ssh version 2
            ssh key-exchange group dh-group14-sha1
            ssh 0 0 management
            ssh timeout 30
            aaa authentication ssh console LOCAL
            username admin password admin privilege 15
            username cisco password cisco privilege 15
            username admin attributes
            service-type admin
            ! required config end
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}

#  ASAvInstance1:
#    Type: "AWS::EC2::Instance"
#    DependsOn: [NetworkInterfaceGIG0,NetworkInterfaceMGMT]
#    Properties:
#      ImageId: { "Fn::FindInMap" : [ "RegionMap", { "Ref" : "AWS::Region" }, "AMI" ]}
#      InstanceType:
#        Ref: InstanceType
#      KeyName: !Ref myKeyPair
#      NetworkInterfaces:
#      - NetworkInterfaceId: !Ref 'NetworkInterfaceMGMT'
#        DeviceIndex: '0'
#      - NetworkInterfaceId: !Ref 'NetworkInterfaceGIG0'
#        DeviceIndex: '1'

Outputs:
  PublicIp:
    Description: ASA Public IP
    Value: !GetAtt ASAvInstance1.PublicIp
    Export:
      Name: !Sub "${AWS::StackName}-ASAPublicIp"